### ISSUE TITLE
Features only option is not working

### ISSUE THREAD

**Issue by RImbriaco** [ZFTurbo/timm_3d#1]
Hi, First I'd like to thank you for your work converting timm into 3D! I was trying to use your library but if I initialize a resnet50 model in 'features_only' mode the function crashes. The output is:

`ValueError: 'NCHW' is not a valid Format` 

However, when trying this with efficientnet B0 I did not run into this issue. 
Any help would be appreciated.

**Comment by ZFTurbo** [comment]
Hello. Can you please post your code how you initilize the model?

**Comment by RImbriaco** [comment]
Thank you for your quick reply. I am sharing a minimal example that shows the problem.

`import timm_3d

# Works fine
convnext = timm_3d.create_model(
    'efficientnet_b0',
    pretrained=True,
    num_classes=0,
    global_pool='',
    features_only=True
)

# Throws error -> ValueError: 'NCHW' is not a valid Format
resnet = timm_3d.create_model(
    'resnet50',
    pretrained=True,
    num_classes=0,
    global_pool='',
    features_only=True
)

# Throws error -> ValueError: 'NCHW' is not a valid Format
convnext = timm_3d.create_model(
    'convnextv2_base',
    pretrained=True,
    num_classes=0,
    global_pool='',
    features_only=True
)`

**Comment by ZFTurbo** [comment]
I did a fix in repo. It should work now.

**Comment by RImbriaco** [comment]
Yup, just tested it and it all runs fine. Thanks!
